<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="System.IO.Abstractions" Version="22.1.0" />
    <PackageVersion Include="System.IO.Abstractions.TestingHelpers" Version="22.1.0" />
    <PackageVersion Include="TUnit" Version="1.41.0" />
    <PackageVersion Include="TUnit.Core" Version="1.41.0" />
  </ItemGroup>
</Project>
