<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.MachineLearning.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Novolis.MachineLearning.AutoMl/Novolis.MachineLearning.AutoMl.csproj" />
    <ProjectReference Include="../../src/Novolis.MachineLearning.Core/Novolis.MachineLearning.Core.csproj" />
    <ProjectReference Include="../../src/Novolis.MachineLearning.Neural.Abstractions/Novolis.MachineLearning.Neural.Abstractions.csproj" />
    <ProjectReference Include="../../src/Novolis.MachineLearning.Neural/Novolis.MachineLearning.Neural.csproj" />
    <ProjectReference Include="../Novolis.MachineLearning.Neural.TestSupport/Novolis.MachineLearning.Neural.TestSupport.csproj" />
    <ProjectReference Include="../Novolis.MachineLearning.TestSupport/Novolis.MachineLearning.TestSupport.csproj" />
  </ItemGroup>
</Project>
