<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Library</OutputType>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>
</Project>
