<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.MachineLearning.Neural</PackageId>
    <Version>0.1.0-preview.1</Version>
    <IsPackable>true</IsPackable>
    <Description>Dense feedforward neural network implementation with training, mutation, and JSON persistence.</Description>
    <RootNamespace>Novolis.MachineLearning.Neural</RootNamespace>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Novolis.MachineLearning.Neural.Abstractions\Novolis.MachineLearning.Neural.Abstractions.csproj" />
    <ProjectReference Include="..\Novolis.MachineLearning.Core\Novolis.MachineLearning.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>
</Project>
